version: 0.2

env:
  variables:
    REGISTRY: "123456789012.dkr.ecr.us-west-1.amazonaws.com"
    TAG: "main"

phases:
  install:
    commands:
      - echo "CodeBuild environment ready"
  pre_build:
    commands:
      - echo "Logging into ECR..."
      - aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin "${REGISTRY}"
      - |
        for svc in ingest matcher signals execution api ui; do
          aws ecr describe-repositories --repository-name "arbitrage-${svc}" >/dev/null 2>&1 || \
          aws ecr create-repository --repository-name "arbitrage-${svc}";
        done
  build:
    commands:
      - chmod +x scripts/build_images.sh
      - ./scripts/build_images.sh
  post_build:
    commands:
      - |
        for svc in ingest matcher signals execution api ui; do
          docker tag "arbitrage-${svc}:${TAG}" "${REGISTRY}/arbitrage-${svc}:${TAG}"
          docker push "${REGISTRY}/arbitrage-${svc}:${TAG}"
        done

artifacts:
  files: []
